[package]
name = "unifont"
version = "0.1.0"
build = "build.rs"
authors = ["Mate Kovacs <mkovaxx@gmail.com>"]
description = "Provides a monochrome Unicode bitmap font. Halfwidth glyphs are 8x16, fullwidth are 16x16 pixels."
homepage = "https://gitlab.com/mkovacs/unifont-rs"
repository = "https://gitlab.com/mkovacs/unifont-rs"
readme = "README.md"
license = "MIT"
keywords = ["monochrome", "unicode", "bitmap", "font", "8x16", "16x16"]
categories = ["encoding"]
exclude = [".gitignore"]

[dependencies]
